sistema/urls.py
from django.contrib import admin
from django.urls import path, include
from sistema.views import Login, Logout

urlpatterns = [
	path('admin/', admin.site.urls),
	path('', Login.as_view(), name='login'),
	path('logout/', Logout.as_view(), name='logout'),
	path('veiculo/', include('veiculo.urls'), name='veiculo')
]

veiculo/urls.py
from django.urls import path
from veiculo.views import ListarVeiculos, FotoVeiculo, CriarVeiculos, EditarVeiculos, APIListarVeiculos

urlpatterns = [
	path('', ListarVeiculos.as_view(), name='listar-veiculos'),
	path('novo/', CriarVeiculos.as_view(), name='criar-veiculos'),
	path('<int:pk>/', EditarVeiculos.as_view(), name='editar-veiculos'),
	path('fotos/<str:arquivo>/', FotoVeiculo.as_view(), name="foto-veiculo"),
	path('api/', APIListarVeiculos.as_view(), name='api-listat-veiculos'),
]

anuncio/models.py
from django.db import models
from veiculo.models import Veiculo
from django.contrib.auth.models import User

class Anuncio(models.Model):
    data = models.DateTimeField(auto_now_add=True)
    descricao = models.CharField(max_length=200)
    preco = models.DecimalField(decimal_places=2, max_digits=10)
    
    veiculo = models.ForeignKey(Veiculo, related_name='anuncios', on_delete=models.CASCADE)
    usuario = models.ForeignKey(User, related_name='anuncios_realizados', on_delete=models.CASCADE)

veiculo/models.py
from django.db import models
from veiculo.consts import *
from datetime import datetime

class Veiculo(models.Model):
	marca = models.SmallIntegerField(choices=OPCOES_MARCAS)
	modelo = models.CharField(max_length=100)
	ano = models.IntegerField()
	cor = models.SmallIntegerField(choices=OPCOES_CORES)
	foto = models.ImageField(blank=True, null=True, upload_to='veiculo/fotos')
	combustivel = models.SmallIntegerField(choices=OPCOES_COMBUSTIVEIS)

	def anos_de_uso(self):
		return datetime.now().year - self.ano
	
	@property
	def veiculo_novo(self) -> bool:
		return self.ano == datetime.now().year

anuncio/forms.py
from django.forms import ModelForm
from anuncio.models import Anuncio

class FormularioAnuncio(ModelForm):
	class Meta:
		model = Anuncio
		exclude = ['usuario']

veiculo/forms.py
from django.forms import ModelForm
from veiculo.models import Veiculo

class FormularioVeiculo(ModelForm):
	class Meta:
		model = Veiculo
		exclude = []

anuncio/views.py
from django.shortcuts import render
from django.views.generic import View, ListView, CreateView, UpdateView, DeleteView
from anuncio.models import Anuncio
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.http.response import FileResponse, Http404
from django.urls import reverse_lazy
from anuncio.forms import FormularioAnuncio

class ListarAnuncios(LoginRequiredMixin, ListView):
	model = Anuncio
	context_object_name = 'anuncios'
	template_name = 'anuncio/listar.html'

class CriarAnuncios(LoginRequiredMixin, CreateView):
	model = Anuncio
	form_class = FormularioAnuncio
	template_name = 'anuncio/novo.html'
	success_url = reverse_lazy('listar-anuncios')

class EditarAnuncios(LoginRequiredMixin, UpdateView):
    model = Anuncio
    form_class = FormularioAnuncio
    template_name = 'anuncio/editar.html'
    success_url = reverse_lazy('listar-anuncios')

class DeletarAnuncios(LoginRequiredMixin, DeleteView):
    model = Anuncio
    template_name = 'anuncio/deletar.html'
    success_url = reverse_lazy('listar-anuncios')

sistema/views.py
from django.conf import settings
from django.views.generic import View
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout

class Login(View):
    """
    """
    def get(self, request):
        contexto = {'mensagem': ''}
        if request.user.is_authenticated:
            return redirect('/veiculo')
        else:
            return render(request, 'autenticacao.html', contexto)

    def post(self, request):
        nome = request.POST.get('nome', None)
        senha = request.POST.get('senha', None)
        
        usuario = authenticate(request, username=nome, password=senha)
        if usuario is not None:
            if usuario.is_active:
                login(request, usuario)
                return redirect("/veiculo")
            return render(request, 'autenticacao.html', {'mensagem': 'Usuário inativo.'})
        return render(request, 'autenticacao.html', {'mensagem': 'Usuário ou senha inválidos.'})

class Logout(View):
    def get(self, request):
        logout(request)
        return redirect(settings.LOGIN_URL)

veiculo/views.py
from django.shortcuts import render
from django.views.generic import View, ListView, CreateView, UpdateView, DeleteView
from veiculo.models import Veiculo
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.http.response import FileResponse, Http404
from django.urls import reverse_lazy
from veiculo.forms import FormularioVeiculo
from veiculo.serializers import SerializadorVeiculos
from rest_framework.generics import ListAPIView
from rest_framework import permissions
from rest_framework.authentication import TokenAuthentication

class ListarVeiculos(LoginRequiredMixin, ListView):
	model = Veiculo
	context_object_name = 'veiculos'
	template_name = 'veiculo/listar.html'

class CriarVeiculos(LoginRequiredMixin, CreateView):
	model = Veiculo
	form_class = FormularioVeiculo
	template_name = 'veiculo/novo.html'
	success_url = reverse_lazy('listar-veiculos')

class EditarVeiculos(LoginRequiredMixin, UpdateView):
    model = Veiculo
    form_class = FormularioVeiculo
    template_name = 'veiculo/editar.html'
    success_url = reverse_lazy('listar-veiculos')

class DeletarVeiculos(LoginRequiredMixin, DeleteView):
    model = Veiculo
    template_name = 'veiculo/deletar.html'
    success_url = reverse_lazy('listar-veiculos')

class FotoVeiculo(View):
	def get(self, request, arquivo):
		try:
			veiculo = Veiculo.objects.get(foto="veiculo/fotos/{}".format(arquivo))
			return FileResponse(veiculo.foto)
		except ObjectDoesNotExist:
			raise Http404
		except Exception as exception:
			raise exception

class APIListarVeiculos(ListAPIView):

	serializer_class = SerializadorVeiculos
	authentication_classes = [TokenAuthentication]
	permission_classes = [permissions.IsAuthenticated]

	def get_queryset(self):
		return Veiculo.objects.all()

templates/autenticacao.html
<!DOCTYPE html>
<html>
	<head>
		{% load static %}
		<style>
			body {
				color: lime;
				font-family: "Lucida Console", "Courier New", monospace;
				font-size: 20px;
			}
			input {
				width: 20%;
				padding: 12px 20px;
				margin: 8px 0;
				box-sizing: border-box;
				border: 1px solid lime;
				outline: none;
				background-color: black;
				color: lime;
				font-size: 20px;
				}
				
			input:focus {
				border: 1px solid blue;
			}
		</style>
	<head>
	<body>
		<form action="/" method="POST">
			{% csrf_token %}
			<label for="nome">Nome</label><br>
			<input type="text" id="nome" name="nome"><br>
			<label for="senha">Senha</label><br>
			<input type="password" id="senha" name="senha"><br>
			<input type="submit" value="Submit"><br>
		</form>

		{% if mensagem %}
		{{ mensagem }}
		{% endif %}
	<body>
</html>

templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<style>
			body {
				color: lime;
				font-family: "Lucida Console", "Courier New", monospace;
				font-size: 20px;
			}

			input {
				width: 20%;
				padding: 12px 20px;
				margin: 8px 0;
				box-sizing: border-box;
				border: 1px solid lime;
				outline: none;
				background-color: black;
				color: lime;
				font-size: 20px;
			}

			input:focus {
				border: 1px solid white;
			}

			input[type="file"] {
				display: none;
			}
			
			.input-file {
				border: 1px solid lime;
				display: inline-block;
				padding: 6px 12px;
				cursor: pointer;
			}

			select {
				width: 20%;
				padding: 12px 20px;
				margin: 8px 0;
				box-sizing: border-box;
				border: 1px solid lime;
				outline: none;
				background-color: black;
				color: lime;
				font-size: 20px;
			}

			select:focus {
				border: 1px solid white;
			}

			button {
				width: 20%;
				padding: 12px 20px;
				margin: 8px 0;
				box-sizing: border-box;
				border: 1px solid lime;
				outline: none;
				background-color: black;
				color: lime;
				font-size: 20px;
			}

			button:focus {
				border: 1px solid white;
			}
		</style>
	<head>
	<body>
		<header>
			<a href="/">Listar</a>
			<a href="/veiculo/novo/">Cadastrar</a>
			<a href="/veiculo/anuncio/">Anúncio</a>
		</header>
		{% block content %}
		{% endblock %}
	<body>
</html>

templates/veiculo/editar.html
{% extends "../base.html" %}
{% block content %}
{% load static %}
<div>
	<form method="post" action="/veiculo/{{object.pk}}/" enctype="multipart/form-data">
		{% csrf_token %}
		<label for="marca">Marca:</label>
		{{ form.marca }}<br>
		<label for="modelo">Modelo:</label>
		{{ form.modelo }}<br>
		<label for="ano">Ano:</label>
		{{ form.ano }}<br>
		<label for="cor">Cor:</label>
		{{ form.cor }}<br>
		<label for="combustivel">Combustivel:</label>
		{{ form.combustivel }}<br>
		<label for="foto">Foto</label>
		<label class="input-file">
			{{ form.foto }}
			Upload
		</label><br>
		<button type="submit">Salvar</button>
	</form>
</div>
{% endblock %}

templates/veiculo/listar.html
{% extends "../base.html" %}
{% block content %}
{% load static %}
Listando o(s) {{veiculos|length}} veículo(s):
{% for veiculo in veiculos %}
<div id="card_{{veiculo.id}}" style="margin-bottom:4vh">
	<img src="{{veiculo.foto.url}}"></img><br>
	Modelo: {{veiculo.modelo}} -- 
	Marca: {{veiculo.get_marca_display}} -- 
	Ano: {{veiculo.ano}} -- 
	Cor: {{veiculo.get_cor_display}} -- 
	Combustivel: {{veiculo.get_combustivel_display}}
	<a href="/veiculo/{{veiculo.id}}"><button>Editar</button></a>
	<hr>
</div>
{% endfor %}
{% endblock %}

templates/veiculo/novo.html
{% extends "../base.html" %}

{% block content %}
<div>
	<form method="post" action="/veiculo/novo/" enctype="multipart/form-data">
		{% csrf_token %}
		<label for="marca">Marca:</label>
		{{ form.marca }}<br>
		<label for="modelo">Modelo:</label>
		{{ form.modelo }}<br>
		<label for="ano">Ano:</label>
		{{ form.ano }}<br>
		<label for="cor">Cor:</label>
		{{ form.cor }}<br>
		<label for="combustivel">Combustivel:</label>
		{{ form.combustivel }}<br>
		<label class="input-file">
			{{ form.foto }}
			Upload
		</label><br>
		<button type="submit">Enviar</button>
	</form>
</div>
{% endblock content %}